name = "prisma-d1-example"
main = "src/index.ts"
compatibility_date = "2024-03-20"
compatibility_flags = ["nodejs_compat"]

//TODO: Fix Remote Connection
[[d1_databases]]
binding = "DB"
database_name = "mealy-prisma-db"
database_id = "04057753-b9fc-4732-bc2c-254049c85d54"